version: '3.8'

services:
  # Servicio de Python (Backend)
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data 
    networks:
      - web_net
      - db_net
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  # Servicio de Node/Nginx (Frontend)
  frontend:
    build: 
      context: ./Fronted
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    networks:
      - web_net

  # Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data 
    networks:
      - db_net

networks:
  web_net:
  db_net:

volumes:
  backend_data: 
  db_data: