version: '3.8'

services:
  # python-backend
  backend:
    build: . 
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data 
    networks:
      - web_net
      - db_net

  # Base de Datos 
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data 
    networks:
      - db_net

# --- DEFINICIÓN DE RECURSOS ---
networks:
  web_net:
  db_net:
  # Eliminamos innovatech_net porque ya no la usamos arriba

volumes:
  backend_data: 
  db_data: # <--- ¡IMPORTANTE! Te faltaba declarar este para la base de datos