# Build Backend
      - name: Build Backend
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          file: ./Backend/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-innovatech:latest

      # Build Frontend
      - name: Build Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./Fronted # <--- Asegúrate que diga Fronted (como tu carpeta)
          file: ./Fronted/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-innovatech:latest